// pixelRenderer.js — ОТРИСОВКА ПИКСЕЛЬНОГО ОРУЖИЯ

function drawPixelWeapon(ctx, weaponId, x, y, size = 64, rotation = 0) {
  const pixelSize = size / 16; // 16x16 базовая сетка
  
  // Пиксельные спрайты (закодированы в строки)
  const PIXEL_SPRITES = {
    ak47: `
      ....██▓▓██....
      ..████▓▓████..
      ..████▓▓████..
      .██████▓▓████..
      .████████████..
      ...░░░░░░░░....
      ...██░░░░██....
      ...████████....
      .....████......
      .....████......
    `,
    
    awp: `
      ......██........
      ....██████......
      ..██████████....
      ..██▓▓▓▓▓▓██....
      ....████████....
      ......████......
      ......████......
      ......░░░░......
      ......░░░░......
    `,
    
    m4a4: `
      ....██▓▓██......
      ..████▓▓████....
      ..████▓▓████....
      .██████▓▓████....
      .████████████....
      ...░░░░░░░░......
      ...██░░░░██......
      ...████████......
      .....█████.......
    `,
    
    deagle: `
      ......██........
      ....██████......
      ....██▓▓██......
      ......████......
      ......░░░░......
      ......░░░░......
      ......░░░░......
    `,
    
    karambit: `
      ......░░........
      ....░░██........
      ....██░░░░......
      ..██░░░░██......
      ..██░░░░██......
      ....████........
    `,
    
    butterfly: `
      ......██........
      ....██████......
      ....██░░██......
      ..██░░░░░░......
      ..██░░░░░░......
      ....██████......
    `
  };
  
  const sprite = PIXEL_SPRITES[weaponId] || PIXEL_SPRITES.ak47;
  const lines = sprite.trim().split('\n');
  
  ctx.save();
  ctx.translate(x, y);
  ctx.rotate(rotation);
  
  // Отрисовка по пикселям
  for (let row = 0; row < lines.length; row++) {
    const line = lines[row];
    for (let col = 0; col < line.length; col++) {
      const char = line[col];
      let color;
      
      switch(char) {
        case '█': color = '#3a3a4a'; break; // Тёмный металл
        case '▓': color = '#5a5a6a'; break; // Светлый металл
        case '░': color = '#8b6914'; break; // Дерево
        case '▓': color = '#ffd700'; break; // Золото (если есть)
        default: continue; // Пропускаем прозрачные
      }
      
      ctx.fillStyle = color;
      ctx.fillRect(
        (col - 8) * pixelSize,
        (row - 8) * pixelSize,
        pixelSize,
        pixelSize
      );
    }
  }
  
  ctx.restore();
}

// Экспорт
window.drawPixelWeapon = drawPixelWeapon;